export type PositionCategory = {
  department: string;
  positions: string[];
};

export const positionCatalog: PositionCategory[] = [
  {
    department: "Executive & Corporate Leadership",
    positions: [
      "Chairman",
      "Vice Chairman",
      "Founder",
      "Co-Founder",
      "President",
      "Executive Vice President",
      "Senior Vice President",
      "Vice President",
      "Chief Executive Officer",
      "Chief Operating Officer",
      "Chief Financial Officer",
      "Chief Technology Officer",
      "Chief Information Officer",
      "Chief Revenue Officer",
      "Chief Marketing Officer",
      "Chief Human Resources Officer",
      "Chief Security Officer",
      "Chief Compliance Officer",
      "Chief Legal Officer",
      "Chief Product Officer",
      "Chief AI Officer",
      "Chief Innovation Officer",
      "Chief Data Officer",
      "Chief Strategy Officer",
      "Chief Experience Officer",
    ],
  },
  {
    department: "Corporate Management",
    positions: [
      "Regional Director",
      "Regional Manager",
      "District Manager",
      "Area Manager",
      "General Manager",
      "Operations Manager",
      "Assistant Operations Manager",
      "Program Director",
      "Program Manager",
      "Project Director",
      "Project Manager",
      "Corporate Trainer",
      "Business Unit Manager",
      "Franchise Manager",
      "Acquisition Manager",
      "Strategic Partnerships Manager",
      "Change Management Specialist",
      "Continuous Improvement Manager",
      "Corporate Analyst",
      "Corporate Consultant",
    ],
  },
  {
    department: "Finance & Accounting",
    positions: [
      "Controller",
      "Assistant Controller",
      "CFO",
      "Senior Accountant",
      "Staff Accountant",
      "Junior Accountant",
      "Cost Accountant",
      "Tax Accountant",
      "Tax Manager",
      "Payroll Manager",
      "Payroll Clerk",
      "Bookkeeper",
      "Accounts Payable Clerk",
      "Accounts Receivable Clerk",
      "Revenue Analyst",
      "Financial Analyst",
      "Senior Financial Analyst",
      "Treasury Manager",
      "Collections Specialist",
      "Billing Specialist",
      "Auditor",
      "Internal Auditor",
      "Budget Analyst",
      "Finance Manager",
      "Credit Analyst",
    ],
  },
  {
    department: "Human Resources",
    positions: [
      "HR Director",
      "HR Manager",
      "HR Generalist",
      "HR Assistant",
      "Recruiter",
      "Senior Recruiter",
      "Talent Acquisition Manager",
      "Onboarding Specialist",
      "Benefits Administrator",
      "Compensation Analyst",
      "Employee Relations Specialist",
      "Workforce Development Manager",
      "Training Coordinator",
      "Learning & Development Manager",
      "Safety Coordinator",
      "HR Compliance Specialist",
      "Retention Specialist",
      "Organizational Development Manager",
      "Career Coach",
      "Internship Coordinator",
    ],
  },
  {
    department: "Legal & Compliance",
    positions: [
      "General Counsel",
      "Corporate Attorney",
      "Litigation Attorney",
      "Compliance Director",
      "Compliance Manager",
      "Compliance Analyst",
      "Risk Manager",
      "Risk Analyst",
      "Contract Administrator",
      "Contract Specialist",
      "Regulatory Affairs Manager",
      "Regulatory Affairs Specialist",
      "Licensing Manager",
      "Licensing Specialist",
      "Trademark Specialist",
      "Patent Analyst",
      "Legal Assistant",
      "Paralegal",
    ],
  },
  {
    department: "Information Technology",
    positions: [
      "CTO",
      "IT Director",
      "IT Manager",
      "Help Desk Technician",
      "Desktop Support Technician",
      "Systems Administrator",
      "Network Administrator",
      "Network Engineer",
      "Cloud Engineer",
      "Cloud Architect",
      "Cybersecurity Analyst",
      "Security Engineer",
      "DevOps Engineer",
      "Site Reliability Engineer",
      "Database Administrator",
      "Database Developer",
      "Data Engineer",
      "Data Scientist",
      "Software Engineer",
      "Senior Software Engineer",
      "Front End Developer",
      "Back End Developer",
      "Full Stack Developer",
      "Mobile Developer",
      "Android Developer",
      "iOS Developer",
      "QA Tester",
      "QA Engineer",
      "QA Manager",
      "Product Manager",
      "Product Owner",
      "Solutions Architect",
      "Enterprise Architect",
      "Technical Writer",
      "IT Trainer",
    ],
  },
  {
    department: "AI & Machine Learning",
    positions: [
      "AI Engineer",
      "AI Research Scientist",
      "Machine Learning Engineer",
      "LLM Engineer",
      "Computer Vision Engineer",
      "Speech Recognition Engineer",
      "Data Annotation Specialist",
      "Prompt Engineer",
      "AI Product Manager",
      "AI Trainer",
      "AI Integration Specialist",
      "AI Quality Analyst",
      "Robotics Engineer",
      "Autonomous Systems Engineer",
      "AI Operations Manager",
      "NLP Engineer",
      "Deep Learning Engineer",
      "AI Ethics Specialist",
      "AI Compliance Analyst",
      "AI Solutions Architect",
    ],
  },
  {
    department: "News, Media & Marketing",
    positions: [
      "Editor In Chief",
      "Managing Editor",
      "Journalist",
      "Investigative Reporter",
      "News Producer",
      "Assignment Editor",
      "Copy Editor",
      "Podcast Host",
      "Radio Host",
      "Anchor",
      "Camera Operator",
      "Video Editor",
      "Drone Photographer",
      "Photographer",
      "Graphic Designer",
      "Creative Director",
      "Brand Manager",
      "Marketing Director",
      "Marketing Manager",
      "Marketing Coordinator",
      "Content Creator",
      "Copywriter",
      "SEO Specialist",
      "PPC Specialist",
      "Social Media Manager",
      "Community Manager",
      "Public Relations Manager",
      "Communications Director",
      "Advertising Specialist",
      "Media Buyer",
    ],
  },
  {
    department: "Real Estate",
    positions: [
      "Real Estate Director",
      "Property Manager",
      "Assistant Property Manager",
      "Regional Property Manager",
      "Leasing Agent",
      "Leasing Manager",
      "Property Inspector",
      "Building Inspector",
      "Facilities Manager",
      "Facilities Coordinator",
      "Construction Manager",
      "Development Manager",
      "Tenant Relations Specialist",
      "Asset Manager",
      "Acquisition Specialist",
      "Disposition Specialist",
      "Land Acquisition Manager",
      "Commercial Broker",
      "Residential Broker",
      "Real Estate Agent",
      "Grounds Supervisor",
      "Groundskeeper",
      "Maintenance Coordinator",
      "Building Engineer",
      "HOA Manager",
    ],
  },
  {
    department: "Construction",
    positions: [
      "Construction Director",
      "Superintendent",
      "Assistant Superintendent",
      "Site Supervisor",
      "Carpenter",
      "Finish Carpenter",
      "Framer",
      "Mason",
      "Concrete Finisher",
      "Drywall Technician",
      "Painter",
      "Flooring Installer",
      "Roofer",
      "Excavation Operator",
      "Equipment Operator",
      "Welder",
      "Ironworker",
      "Laborer",
      "Site Safety Officer",
      "Construction Estimator",
      "Construction Scheduler",
      "Project Engineer",
      "Construction Coordinator",
      "Survey Technician",
      "Demolition Technician",
    ],
  },
  {
    department: "Electrical",
    positions: [
      "Master Electrician",
      "Journeyman Electrician",
      "Apprentice Electrician",
      "Electrical Engineer",
      "Electrical Designer",
      "Electrical Estimator",
      "Controls Technician",
      "PLC Programmer",
      "Industrial Electrician",
      "Solar Technician",
      "Renewable Energy Technician",
      "Electrical Project Manager",
    ],
  },
  {
    department: "Plumbing & HVAC",
    positions: [
      "Master Plumber",
      "Journeyman Plumber",
      "Apprentice Plumber",
      "Plumbing Estimator",
      "HVAC Technician",
      "HVAC Installer",
      "Refrigeration Technician",
      "Boiler Technician",
      "Pipefitter",
      "Steamfitter",
      "Mechanical Technician",
      "Indoor Air Quality Specialist",
      "Energy Auditor",
      "Service Dispatcher",
      "Mechanical Project Manager",
    ],
  },
  {
    department: "Automotive",
    positions: [
      "Service Manager",
      "Assistant Service Manager",
      "Shop Foreman",
      "Service Advisor",
      "Master Technician",
      "Diagnostic Technician",
      "Diesel Technician",
      "Fleet Technician",
      "Transmission Technician",
      "Engine Specialist",
      "Hybrid Technician",
      "EV Technician",
      "Alignment Technician",
      "Tire Technician",
      "Lube Technician",
      "Detail Technician",
      "Collision Technician",
      "Auto Body Technician",
      "Painter",
      "Paint Prep Technician",
      "Parts Manager",
      "Parts Specialist",
      "Warranty Administrator",
      "Service Dispatcher",
      "Tow Truck Operator",
      "Roadside Assistance Technician",
      "Vehicle Inspector",
      "Fleet Manager",
      "Automotive Trainer",
      "Technical Support Specialist",
    ],
  },
  {
    department: "Auto Sales",
    positions: [
      "General Sales Manager",
      "Sales Manager",
      "Finance Manager",
      "F&I Director",
      "Sales Consultant",
      "Internet Sales Specialist",
      "BDC Representative",
      "Vehicle Acquisition Specialist",
      "Title Clerk",
      "Registration Clerk",
      "Lot Manager",
      "Inventory Manager",
      "Vehicle Photographer",
      "Delivery Coordinator",
      "Customer Experience Manager",
      "Leasing Consultant",
      "Fleet Sales Manager",
      "Commercial Sales Manager",
      "Used Car Manager",
      "New Car Manager",
    ],
  },
  {
    department: "Manufacturing & Machine Shop",
    positions: [
      "Plant Manager",
      "Production Manager",
      "Production Supervisor",
      "Manufacturing Engineer",
      "Industrial Engineer",
      "CNC Machinist",
      "CNC Programmer",
      "Lathe Operator",
      "Mill Operator",
      "Tool & Die Maker",
      "Fabricator",
      "Welder",
      "Machine Operator",
      "Assembly Technician",
      "Quality Inspector",
      "Quality Manager",
      "Production Planner",
      "Inventory Coordinator",
      "Shipping Coordinator",
      "Receiving Coordinator",
      "Maintenance Technician",
      "Industrial Electrician",
      "Prototype Technician",
      "Packaging Technician",
      "Process Engineer",
    ],
  },
  {
    department: "Restaurants & Food Service",
    positions: [
      "Restaurant Director",
      "Restaurant Manager",
      "Assistant Manager",
      "Executive Chef",
      "Sous Chef",
      "Kitchen Manager",
      "Line Cook",
      "Prep Cook",
      "Dishwasher",
      "Baker",
      "Pastry Chef",
      "Server",
      "Host",
      "Bartender",
      "Catering Manager",
      "Banquet Manager",
      "Food Runner",
      "Expeditor",
      "Shift Leader",
      "Bar Manager",
      "Beverage Manager",
      "Purchasing Manager",
      "Inventory Specialist",
      "Restaurant Trainer",
      "Franchise Support Manager",
    ],
  },
  {
    department: "Hospitality & Hotels",
    positions: [
      "Hotel General Manager",
      "Front Desk Manager",
      "Front Desk Agent",
      "Concierge",
      "Housekeeper",
      "Housekeeping Supervisor",
      "Event Coordinator",
      "Event Manager",
      "Banquet Coordinator",
      "Banquet Server",
      "Guest Services Manager",
      "Reservation Agent",
      "Revenue Manager",
      "Hospitality Trainer",
      "Shuttle Driver",
      "Valet",
      "Maintenance Technician",
      "Security Officer",
      "Director of Sales",
      "Hotel Controller",
    ],
  },
  {
    department: "Barbering & Cosmetology",
    positions: [
      "Salon Director",
      "Salon Manager",
      "Master Barber",
      "Barber",
      "Apprentice Barber",
      "Cosmetologist",
      "Hair Stylist",
      "Nail Technician",
      "Esthetician",
      "Massage Therapist",
      "Receptionist",
      "Salon Coordinator",
      "Product Specialist",
      "Salon Educator",
      "Salon Assistant",
    ],
  },
  {
    department: "Security & Investigations",
    positions: [
      "Security Director",
      "Security Manager",
      "Security Supervisor",
      "Security Officer",
      "Armed Security Officer",
      "Loss Prevention Specialist",
      "Corporate Investigator",
      "Fraud Investigator",
      "Surveillance Operator",
      "Security Analyst",
      "Executive Protection Specialist",
      "Event Security Officer",
      "Access Control Technician",
      "Intelligence Analyst",
      "Emergency Management Coordinator",
    ],
  },
  {
    department: "Logistics & Transportation",
    positions: [
      "Logistics Director",
      "Transportation Manager",
      "Fleet Manager",
      "Dispatcher",
      "Logistics Coordinator",
      "CDL Driver",
      "Delivery Driver",
      "Warehouse Manager",
      "Warehouse Supervisor",
      "Warehouse Associate",
      "Shipping Clerk",
      "Receiving Clerk",
      "Inventory Specialist",
      "Route Planner",
      "Freight Broker",
      "Yard Manager",
      "Forklift Operator",
      "Supply Chain Analyst",
      "Procurement Specialist",
      "Purchasing Manager",
    ],
  },
  {
    department: "Aviation & Drones",
    positions: [
      "Chief Pilot",
      "Commercial Pilot",
      "Drone Pilot",
      "Drone Inspector",
      "Drone Mapping Specialist",
      "UAV Operations Manager",
      "Aviation Mechanic",
      "Avionics Technician",
      "Aircraft Maintenance Technician",
      "Flight Operations Coordinator",
      "Flight Instructor",
      "Airport Operations Manager",
      "Aerospace Engineer",
      "Aerodynamics Engineer",
      "Flight Test Engineer",
      "Aircraft Painter",
      "Aircraft Fabrication Technician",
      "Air Traffic Liaison",
      "Aviation Safety Manager",
      "UAV Software Engineer",
    ],
  },
  {
    department: "Energy & Utilities",
    positions: [
      "Energy Manager",
      "Utility Technician",
      "Solar Installer",
      "Wind Turbine Technician",
      "Energy Analyst",
      "Renewable Energy Engineer",
      "Power Systems Engineer",
      "Generator Technician",
      "Battery Systems Engineer",
      "Electrical Grid Analyst",
      "Utility Operator",
      "Water Systems Technician",
      "Natural Gas Technician",
      "Sustainability Coordinator",
      "Environmental Compliance Manager",
    ],
  },
  {
    department: "Water, Environmental & Waste Management",
    positions: [
      "Water Treatment Operator",
      "Wastewater Operator",
      "Environmental Engineer",
      "Environmental Scientist",
      "Environmental Compliance Officer",
      "Recycling Coordinator",
      "Waste Collection Driver",
      "Waste Management Supervisor",
      "Landfill Operations Manager",
      "Water Quality Analyst",
      "Stormwater Technician",
      "Hazardous Materials Technician",
      "Sustainability Specialist",
      "Conservation Specialist",
      "Environmental Inspector",
      "Water Systems Designer",
      "Water Distribution Technician",
      "Utility Locator",
      "Field Technician",
      "Environmental Project Manager",
    ],
  },
  {
    department: "Administrative & Support",
    positions: [
      "Executive Assistant",
      "Administrative Assistant",
      "Office Manager",
      "Receptionist",
      "Data Entry Clerk",
      "Records Coordinator",
      "Customer Service Representative",
      "Call Center Agent",
      "Call Center Supervisor",
      "Office Clerk",
      "Scheduler",
      "Appointment Coordinator",
      "Document Specialist",
      "Mailroom Clerk",
      "Filing Clerk",
      "Purchasing Assistant",
      "Operations Assistant",
      "Virtual Assistant",
      "Research Assistant",
      "Executive Coordinator",
    ],
  },
  {
    department: "Facilities & Maintenance",
    positions: [
      "Facilities Director",
      "Facilities Manager",
      "Maintenance Supervisor",
      "Maintenance Technician",
      "Building Technician",
      "Janitor",
      "Custodian",
      "Groundskeeper",
      "Landscaping Technician",
      "Snow Removal Technician",
      "Facilities Coordinator",
      "Painter",
      "Handyman",
      "Property Care Technician",
      "Preventive Maintenance Technician",
    ],
  },
];

const uniquePositions = new Set<string>();
for (const category of positionCatalog) {
  for (const position of category.positions) {
    uniquePositions.add(position);
  }
}

export const positions = [...uniquePositions].sort();
